### ISSUE TITLE
API Key in repo

### ISSUE THREAD

**Issue by LukeChannings** [pograjak/pubpap#1]
Hey,

I noticed your API key is committed to the repo [here](https://github.com/pograjak/pubpap/blob/master/nuxt.config.js#L55).

I'm not sure if it's genuine, but if it is, it could be used by malicious parties to publish to https://pubpap-redcute.firebaseapp.com without your permission.

Kind regards,

Luke

**Comment by tomas2211** [comment]
Hi,
thanks for the notice! I deleted the file from the whole repo history using BFG.
Tomas
